id: P001703
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5903
  title: ཏུན་ཧོང་ནས་ཐོན་པའི་བོད་ཀྱི་གསོ་རིག་ཡིག་ཆ་བདམས་བསྒྲིགས་།
  author: ''
  volumes:
    f48822856303485bb2839c29ecaa7cea:
      image_group_id: I1KG5921
      title: ''
      volume_number: 1
      total_pages: 138
      base_file: v001.txt
